### PR TITLE
fix: #117 Provide a usage example for t(options) signature

### LINKED ISSUE #117: Provide a usage example for `t(options)` signature
It would be helpful to have example usage for the third signature of the `t()` method:

image

image

image

### PR DESCRIPTION
**Pull request by yiliang114**
Close #117

### CODE REVIEW

File: l10n/src/main.ts [hunk 1]
```diff
@@ -143,6 +143,7 @@ export function t(strs: TemplateStringsArray, ...replacements: L10nReplacement[]
  * value will be returned (with injected args values for any templated values).
  * @param options - The options to use when localizing the message.
  * @returns localized string with injected arguments.
+ * @example `l10n.t({ message: 'Hello {name}', args: { name: 'Erich' }, comment: 'This is a comment' } );`
```
Comment (TylerLeonhardt) [inline l10n/src/main.ts:146]:
```suggestion
 * @example `l10n.t({ message: 'Hello {0}', args: ['Erich'], comment: 'This is a comment' } );`
```

I'd prefer this syntax to be used in the example.

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Thank you so much for contributing! (just waiting on 1 more review from the team)

**Review by connor4312 — APPROVED** [review]
